CREATE TABLE offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    availability VARCHAR(1000),
    available_quantity INTEGER,
    bgg_id INTEGER,
    bgg_rating NUMERIC(5, 2),
    bgg_status ENUM('ERROR', 'FOUND', 'NOT_CONFIGURED', 'NOT_FOUND', 'NOT_REQUESTED', 'SKIPPED') NOT NULL,
    bgg_want_in_trade INTEGER,
    bgg_want_to_buy INTEGER,
    comparison_available_price NUMERIC(12, 2),
    comparison_best_price NUMERIC(12, 2),
    comparison_status ENUM('ERROR', 'FOUND', 'NOT_CONFIGURED', 'NOT_FOUND', 'NOT_REQUESTED', 'SKIPPED') NOT NULL,
    comparison_url VARCHAR(1500),
    enriched_at TIMESTAMP(6) WITH TIME ZONE,
    first_seen_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    image_url VARCHAR(2000),
    last_changed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(500) NOT NULL,
    notification_fingerprint VARCHAR(1000),
    notified_at TIMESTAMP(6) WITH TIME ZONE,
    price NUMERIC(12, 2),
    source ENUM('MILAN', 'SPIELE_OFFENSIVE', 'UNKNOWNS') NOT NULL,
    source_url VARCHAR(1500) NOT NULL,
    total_quantity INTEGER,
    type ENUM('FORUM_POST', 'GROUP_DEAL', 'SPIELESCHMIEDE', 'STANDARD') NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uk_offer_source_url UNIQUE (source, source_url)
);

CREATE INDEX idx_offer_last_seen ON offers(last_seen_at);
CREATE INDEX idx_offer_last_changed ON offers(last_changed_at);
CREATE INDEX idx_offer_bgg_status ON offers(bgg_status);
CREATE INDEX idx_offer_comparison_status ON offers(comparison_status);

CREATE TABLE activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bgg_status ENUM('ERROR', 'FOUND', 'NOT_CONFIGURED', 'NOT_FOUND', 'NOT_REQUESTED', 'SKIPPED'),
    comparison_status ENUM('ERROR', 'FOUND', 'NOT_CONFIGURED', 'NOT_FOUND', 'NOT_REQUESTED', 'SKIPPED'),
    current_price NUMERIC(12, 2),
    detail VARCHAR(1000),
    image_url VARCHAR(2000),
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    offer_id BIGINT,
    offer_name VARCHAR(500),
    previous_price NUMERIC(12, 2),
    source ENUM('MILAN', 'SPIELE_OFFENSIVE', 'UNKNOWNS'),
    type ENUM('HTTP_RETRY', 'LOOKUP_RETRY', 'OFFER_FOUND', 'PRICE_CHANGED', 'TELEGRAM_FAILED', 'TELEGRAM_SENT') NOT NULL
);

CREATE INDEX idx_activity_occurred_at ON activity_log(occurred_at);
CREATE INDEX idx_activity_type ON activity_log(type);
