ALTER TABLE offers ADD COLUMN source_offer_id VARCHAR(128);
ALTER TABLE offers ALTER COLUMN source SET DATA TYPE ENUM('BGG_MARKET', 'MILAN', 'SPIELE_OFFENSIVE', 'UNKNOWNS');
ALTER TABLE activity_log ALTER COLUMN source SET DATA TYPE ENUM('BGG_MARKET', 'MILAN', 'SPIELE_OFFENSIVE', 'UNKNOWNS');

ALTER TABLE offers ADD CONSTRAINT uk_offer_source_offer_id UNIQUE (source, source_offer_id);
