ALTER TABLE activity_log ADD COLUMN notification_sent BOOLEAN;
ALTER TABLE activity_log ALTER COLUMN detail VARCHAR(10000);
ALTER TABLE activity_log ALTER COLUMN type SET DATA TYPE ENUM('APPLICATION_STARTED', 'BEST_PRICE_WITHHELD', 'HTTP_RETRY', 'LOOKUP_RETRY', 'OFFER_FOUND', 'OFFER_SENT', 'PRICE_CHANGED', 'TELEGRAM_FAILED', 'TELEGRAM_SENT');
UPDATE activity_log SET notification_sent = TRUE WHERE type IN ('OFFER_SENT', 'TELEGRAM_SENT');
UPDATE activity_log SET notification_sent = FALSE WHERE type IN ('BEST_PRICE_WITHHELD', 'TELEGRAM_FAILED');
