ALTER TABLE offers ADD COLUMN notification_status VARCHAR(32) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE offers ADD COLUMN notification_reason VARCHAR(2000);
ALTER TABLE offers ADD COLUMN notification_decided_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE offers ADD COLUMN notification_error VARCHAR(1000);

ALTER TABLE activity_log ALTER COLUMN type SET DATA TYPE ENUM('APPLICATION_STARTED', 'BEST_PRICE_WITHHELD', 'HTTP_RETRY', 'LOOKUP_RETRY', 'NOTIFICATION_DEFERRED', 'NOTIFICATION_WITHHELD', 'OFFER_FOUND', 'OFFER_SENT', 'PRICE_CHANGED', 'TELEGRAM_FAILED', 'TELEGRAM_SENT');
CREATE INDEX idx_activity_offer_occurred_at ON activity_log(offer_id, occurred_at);
